// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfqlxmhstzvxdvpznjez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmcWx4bWhzdHp2eGR2cHpuamV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NDI1NDksImV4cCI6MjA1MjAxODU0OX0.tzbcWYodVcH-w-CKLdaNB-F36md8pTKnxucvG6IVMhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);